### ISSUE TITLE
Importing Components

### ISSUE THREAD

**Issue by cyouh95** [Nazgulbunny/Jamming-React#1]
Don't forget to specify the component during import. For example, in **TrackList.js**:

```js
import Track from '../Track/Track.js';
```

Also check **SearchResults.js** and **Playlist.js** as well.

https://github.com/Nazgulbunny/Jamming-React/blob/master/src/Components/TrackList/TrackList.js#L3

**Comment by Nazgulbunny** [comment]
Hi,
I have corrected the import method in all mentionated files, and I pushed to master.
Nontheless now when I search for artist or albums I get this error again:

INVALID_CLIENT: Invalid redirect URI

**Comment by cyouh95** [comment]
Hi there! If you go to https://beta.developer.spotify.com/dashboard/applications and click on your application, then click "Edit Settings" and under **Redirect URIs**, does what you have there match this line you have here:
https://github.com/Nazgulbunny/Jamming-React/blob/master/src/util/Spotify.js#L7

**Comment by Nazgulbunny** [comment]
Hi, thanks, but sadly I tried this already when I put https://localhost:3000 in the redirect uri  and I try to search for an album or artist I get : 
This site can’t be reached
localhost unexpectedly closed the connection.
