### ISSUE TITLE
Capitalize Components

### ISSUE THREAD

**Issue by cyouh95** [Nazgulbunny/Jamming-React#2]
React Components should be capitalized. For example, in **TrackList.js**:

```js
<Track ... / >
```

Also check **SearchResults.js** and **Playlist.js** as well.

https://github.com/Nazgulbunny/Jamming-React/blob/master/src/Components/TrackList/TrackList.js#L11

**Comment by Nazgulbunny** [comment]
All the components have been capitalized :)
