### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [Nazgulbunny/Jamming-React#5]
(Meets Expectations)

Great job on this project! It looks like you have a good understanding of the overall structure of the app as well as each individual components. Just be careful on importing your components and also make sure to capitalize them (#1, #2).

Nice work with the requests to the Spotify API as well as logging to the console to keep track of the status. As a further challenge, continue to explore the Spotify API and see if you're able to add more features to this app. As you do, be sure to pay attention to the required parameters for making a request to an endpoint, and make sure they are included so it does not result in an error (#3). Happy coding!

**Comment by Nazgulbunny** [comment]
Thanks!
